/*
*	Creates enemies on the level. One file for the whole world... will be broken up at runtime. 
*	Format: position, sprite type
*/

#include "world_0_sprites.h"
#include <gb/gb.h>
#include "../sprite.h"

const UBYTE world_0_egg_counts[] = 			{ 3U, 	2U, 	4U, 	2U};
const UBYTE world_0_start_positions[] =		{ 0U, 	21U, 	2U,		4U};
const UBYTE world_0_x_start_positions[] = 	{ 36U, 	36U, 	36U,	36U};
const UBYTE world_0_y_start_positions[] = 	{ 36U, 	36U, 	36U, 	36U};

const UBYTE world_0_data[1] = { 
	3U // Total eggs
};

const UBYTE NO_SPRITES[1] = { 255U };

const UBYTE DOUBLE_SPIDER[] = {
	22U, (UBYTE)SPRITE_TYPE_SPIDER,
	27U, (UBYTE)SPRITE_TYPE_SPIDER,
	56U, (UBYTE)SPRITE_TYPE_EGG, 
	255U
};

const UBYTE ROOM_OF_SPIDERS[] = {
	27U, (UBYTE)SPRITE_TYPE_SPIDER,
	47U, (UBYTE)SPRITE_TYPE_EGG,
	67U, (UBYTE)SPRITE_TYPE_SPIDER, 
	255U
};

const UBYTE ONE_MONSTER[] = {
	27U, (UBYTE)SPRITE_TYPE_SPIDER,
	255U
};

const UBYTE ESCAPEH[] = {
	17U, (UBYTE)SPRITE_TYPE_SPIDER,
	12U, (UBYTE)SPRITE_TYPE_SPIDER,
	46U, (UBYTE)SPRITE_TYPE_EGG,
	255U
};

const UBYTE ROOM_2_0[] = {
	47U, SPRITE_TYPE_SPIDER,
	63U, SPRITE_TYPE_SPIDER,
	64U, SPRITE_TYPE_CRAB, // GIANT ENEMY CRAB APPEARS!!
	66U, SPRITE_TYPE_EGG,
	255U
};

const UBYTE ROOM_2_1[] = {
	28U, SPRITE_TYPE_SPIDER,
	64U, SPRITE_TYPE_SPIDER,
	24U, SPRITE_TYPE_CRAB,
	36U, SPRITE_TYPE_EGG,
	255U
};

const UBYTE RIVERSIDE_1[] = {
	17U, SPRITE_TYPE_SPIDER,
	77U, SPRITE_TYPE_SPIDER,
	47U, SPRITE_TYPE_EGG,
	255U
};

const UBYTE RIVERSIDE_2[] = {
	57U, SPRITE_TYPE_SPIDER,
	66U, SPRITE_TYPE_SPIDER,
	62U, SPRITE_TYPE_EGG,
	255U
};

const UBYTE CRABWALK_0[] = {
	52U, SPRITE_TYPE_SPIDER,
	25U, SPRITE_TYPE_SPIDER,
	18U, SPRITE_TYPE_CRAB,
	255U
};

const UBYTE CRABWALK_1[] = {
	25U, SPRITE_TYPE_SPIDER,
	57U, SPRITE_TYPE_EGG,
	54U, SPRITE_TYPE_SPIDER,
	10U, SPRITE_TYPE_CRAB,
	255U
};

const UBYTE CRABWALK_2[] = {
	52U, SPRITE_TYPE_EGG,
	21U, SPRITE_TYPE_SPIDER,
	26U, SPRITE_TYPE_SPIDER,
	28U, SPRITE_TYPE_CRAB,
	255U
};

const UBYTE CRABWALK_3[] = {
	25U, SPRITE_TYPE_SPIDER,
	54U, SPRITE_TYPE_SPIDER,
	10U, SPRITE_TYPE_CRAB,
	255U
};

const UBYTE* world_0_sprites[] = {
	NO_SPRITES, 		ROOM_OF_SPIDERS,ROOM_2_0, 			ROOM_2_0, 			CRABWALK_0, 		CRABWALK_1, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	DOUBLE_SPIDER,	 	NO_SPRITES, 	ESCAPEH,	 		ROOM_2_1, 			CRABWALK_2, 		CRABWALK_3, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	ESCAPEH, 			RIVERSIDE_1, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	NO_SPRITES, 		RIVERSIDE_2, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES
};