/*
*	Creates enemies on the level. One file for the whole world... will be broken up at runtime. 
*	Format: position, sprite type
*/

#include "world_0_sprites.h"
#include <gb/gb.h>
#include "../sprite.h"

const UBYTE NO_SPRITES[1] = { 255U };

/*const UBYTE CALIBRATION_ROOM[] {
	0U, (UBYTE)SPRITE_TYPE_SPIDER,
	9U, (UBYTE)SPRITE_TYPE_SPIDER,
	70U, (UBYTE)SPRITE_TYPE_SPIDER,
	79U, (UBYTE)SPRITE_TYPE_SPIDER,
	255U
};*/

const UBYTE ROOM_OF_SPIDERS[] = {
	22U, (UBYTE)SPRITE_TYPE_SPIDER,
	27U, (UBYTE)SPRITE_TYPE_SPIDER, 
	255U
};

const UBYTE ONE_MONSTER[] = {
	27U, (UBYTE)SPRITE_TYPE_SPIDER,
	255U
};

const UBYTE* world_0_sprites[] = {
	NO_SPRITES, 		ONE_MONSTER, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	ROOM_OF_SPIDERS, 	NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES,
	NO_SPRITES, 		NO_SPRITES, 	NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES, 		NO_SPRITES
};