#ifndef HELPER_1_H
#define HELPER_1_H
#include <gb/gb.h>
	void handle_input();
	void update_health();
	void pause_loop();
	void do_player_movey_stuff();
	void directionalize_sprites();
	void test_sprite_collision();
	void clear_extra_sprites();
	void init_vars();
	void finish_init_screen();
	void update_egg();
	void test_for_egg();
	void move_sprites_for_load();
	UBYTE get_collision_with_temp3();
	void animate_exit();
	void write_map_to_memory();
	void move_enemy_sprite();
#endif